imports:
    - { resource: parameters.yml }
    - { resource: infrastructure/logger.yml }
    - { resource: infrastructure/swiftmailer.yml }
    - { resource: infrastructure/fos_user.yml }
    - { resource: infrastructure/cache.yml }
    - { resource: infrastructure/lock.yml }
    - { resource: infrastructure/storage.yml }
    - { resource: infrastructure/knp_pagination.yml }
    - { resource: infrastructure/aws.yml }
    - { resource: web/assetic.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: data/us_state.yml }
    - { resource: "@InfrastructureBundle/Resources/config/services.yml" }
    - { resource: "@DataBundle/Resources/config/services.yml" }
    - { resource: "@DomainBundle/Resources/config/services.yml" }
    - { resource: "@PublicBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.sessions_dir%'
    fragments: ~
    http_method_override: true
    assets: ~
    templating:
        engines: ['twig']
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['custom_bootstrap_3_layout.html.twig']
    paths:
        '%kernel.project_dir%/src/FMT/DomainBundle/Resources/views': DomainBundle
    globals:
        marketing_app_url: '%marketing_app_url%'
        google_analytics_id: '%google_analytics_id%'
        social_facebook_link: '%social_facebook_link%'
        social_twitter_link: '%social_twitter_link%'
        social_linkedin_link: '%social_linkedin_link%'
        social_instagram_link: '%social_instagram_link%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
            datetime: FMT\DataBundle\Doctrine\Extensions\DBAL\Types\UTCDateTimeType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                date_format: FMT\DataBundle\Doctrine\DQL\DateFormat
            numeric_functions:
                rand: DoctrineExtensions\Query\Mysql\Rand
        mappings:
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable
                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree
                is_bundle: false

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            loggable: true
    class:
        loggable: FMT\DomainBundle\Listener\LoggableListener
