# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    always_authenticate_before_granting: true
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_DONOR: ROLE_USER
        ROLE_STUDENT: ROLE_USER
        ROLE_INCOMPLETE_STUDENT: ROLE_USER
        ROLE_INCOMPLETE_DONOR: ROLE_USER

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            logout_on_user_change: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: FMT\PublicBundle\Service\Security\AuthenticationHandler
                failure_handler: FMT\PublicBundle\Service\Security\AuthenticationHandler

            logout:
                handlers:
                    - FMT\PublicBundle\Service\Security\AuthenticationHandler
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 31536000
                path: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
