services:
    _defaults:
        autowire: true
        autoconfigure: true

    FMT\InfrastructureBundle\Service\Payments\Dwolla\OptionsInterface: '@FMT\InfrastructureBundle\Service\Payments\Dwolla\Options'
