framework:
    cache:
        default_redis_provider: "%cache_server%"
        default_memcached_provider: "%cache_server%"
        pools:
            fmt.cache:
                adapter: "cache.adapter.%cache_adapter%"
                public: true
                default_lifetime: 3600

services:
    FMT\DomainBundle\Type\Cache\Settings:
        properties:
            nebookCatalogTimeout: "%nebook_cache_lifetime%"