swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    port: "%mailer_port%"

services:
    fmt.mailer:
        alias: mailer
        public: true